name: Update Combined Heatmap

on:
  schedule:
    # Every day at 1 am UTC
    - cron: '0 1 * * *'
  workflow_dispatch:    # allow manual runs

jobs:
  update-heatmap:
    runs-on: ubuntu-latest

    steps:
      # 1) grab your code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # so we can push back

      # 2) set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil svgwrite

      # 4) generate the SVG heatmap
      - name: Generate combined heatmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
        run: python generate_heatmap.py

      # 5) commit & push if it changed
      - name: Commit and push heatmap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add combined-heatmap.svg
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "chore: update combined contributions heatmap"
            git push
          fi
